### ISSUE TITLE
I am facing trouble using multiple product gallery carousels per page. How should I achieve that? Please suggest and share code if possible. 

### ISSUE THREAD

**Issue by payafterwork** [k1ngzed/products-gallery-carousel-with-zoom#1]

**Comment by shoha-kh** [comment]
Added changes to work with multiple carousels!

If you want to embed in the old code, just use .each() for an example, see the code [js/main.js](https://github.com/k1ngzed/products-gallery-carousel-with-zoom/blob/8022fcbc74667059a0eba58132cf7d6fea922460/js/main.js#L3)
