### ISSUE TITLE
Vertical thumbnails

### ISSUE THREAD

**Issue by iamsahilvhora** [k1ngzed/products-gallery-carousel-with-zoom#2]
Is there any way to move the thumbnails to the left and the "gallery-top" to the right?

**Comment by shoha-kh** [comment]
Order to place them on the **right** or **left**, you need to study the swiper plugin. The swiper plugin has a [direction: "vertical"](https://swiperjs.com/demos#vertical) property, which will solve your question. After that, it remains only to correct the css.
