### ISSUE TITLE
How to show thumbnail images to the next line if there are many images

### ISSUE THREAD

**Issue by faisal95bd** [k1ngzed/products-gallery-carousel-with-zoom#3]
Hi, 

for example, I have 7 images. Now in the first line, I want to show 4 thumbnail images, and the rest 3, I want to show them in the next line?
[ScreenShot](https://prnt.sc/1xwwevp)
How can I do that?

**Comment by faisal95bd** [comment]
No updates so far... 🙄

**Comment by shoha-kh** [comment]
The easiest option is to use css. Remove the position: absolute; from the images and remove the fixed height.

```
.gallery-thumbs {
    height: auto !important;
}

.gallery-thumbs > .swiper-wrapper {
    transform: none !important;
    flex-wrap: wrap;
}

.product__carousel .gallery-thumbs .swiper-slide img {
    position: relative;
    max-width: 100%;
    max-height: 170px;
}
```
